### PR TITLE
op 1.33

### PR DESCRIPTION
**Pull request by gits68**
* code auditing using flawfinder, cppcheck, cpplint.py and scan-build.
* Replaced strcpy/strcat by strlcpy/strlcat which are also provided if missing.
* Provided v/snprintf if missing.
* Replaced atoi by strtolong (util.c), atov still provided but unused.
* contrib dir added for various building and packaging architectures
  (aix, hp-ux, linux, solaris). results goes to build and packages dirs.
* autoconf-archive macros added to m4 dir to enhance autotools configuration
  such as compiler flags for hardening building.
* automake scripts moves to build-aux dir.
* Replaced v8 regexp by POSIX regex if possible.

### CODE REVIEW

**Comment by dagwieers** [comment]
Thanks for this pull request, however I am not the original author.
Let's first discuss with the original author where/how this codebase is best improved.

**Comment by gits68** [comment]
well, you're right, I though you were the current maintainer...
however, the home page of alec thomes didn't reference op anywhere or I'm blind :)

**Comment by dagwieers** [comment]
@gits68 Indeed not. But Alec Thomas *is* on GitHub as @alecthomas, and David Koblas as @koblas !
But I cannot find Howard Owen though.

**Comment by koblas** [comment]
I'm not qualified, when I originally wrote op it was effectively one file about 500 lines long, with a few libraries pulled into the original archive. Glad to see that it's still loved by some.

**Comment by gits68** [comment]
IMHO, op is somewhat better than sudo, in configuration possibilities at least, it may check well arguments using regexp where sudo only support positionned arguments or everything else (*).
well, I propose a re implementation to sudo, but not integrated yet I think :-(
https://www.sudo.ws/pipermail/sudo-workers/2016-March/000956.html
nevertheless, the backend is even more advanced than op.
one big missing op feature is X11 forwarding as su, sudo and ssh does it.
for instance, I implement it using shell...

**Comment by dagwieers** [comment]
I received feedback from Howard Owen:

*Thanks for asking, Dag. My contributions were relatively minor and I haven't touched op in 25 years. The code was released under a BSD-like license, which requires that a copyright notice be retained with modified versions. For my changes, I waive that requirement.  If you're talking about the GPL, then so much the better, but I'm perfectly OK with you relicensing op as you see fit.*

I was only hinting to a change in license in my mail, because it may influence for future adoption and continuous development for some. And since it is no longer maintained the question is more than ever relevant.

**Comment by dagwieers** [comment]
@gits68 Let's merge this PR. If you want to become the maintainer of op, let me know. I do not consider myself the maintainer, maybe a custodian :-)

**Comment by gits68** [comment]
well, I've so many time for now, but maybe later, thanks.

**Pull request merged**
